config/routes.rb
Rails.application.routes.draw do
  resources :userprojects
  get 'static_pages/home'

  resources :todo_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root   "users#home"
  get    '/users',        to: 'users#index' 
  get    '/users/edit',   to: 'users#edit'
  get    '/home',         to: 'users#home'
  get    '/signup',       to: 'users#new'
  get    'users/login',   to: 'sessions#new'
  post   'users/login',   to: 'sessions#create'
  delete 'users/logout',  to: 'sessions#destroy'
  resources :users

  root "users#new"
  get '/users',       to: 'users#index' 
  get '/users/new',   to: 'users#new'
  get '/users/edit',  to: 'users#edit'
  get '/users/signup',    to: 'users#signup'
resources :todo_lists do
   resources :todo_items do
    member do
     patch :complete
    end
  end
end


  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects,            only: [:create, :destroy]
  resources :following,           only: [:create, :destroy]
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :project
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 140 }
  
def completed?
   !completed_at.blank?
end

def build
    
end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
 before_action :set_todo_list
 before_action :set_todo_item, except: [:create]
 
def create
 @todo_item = @todo_list.todo_items.create(todo_item_params)
 redirect_to @todo_list
end

def show
    @todo_lists = TodoList.find(params[:id]) 
    @todo_items = TodoItem.find_by(todo_list: params[:id])
end

def destroy
 @todo_item = @todo_list.todo_items.find(params[:id])
 if @todo_item.destroy
  flash[:success] = "Todo List item was deleted."
 else
  flash[:error] = "Todo List item could not be deleted."
 end
 redirect_to @todo_list 
end

def complete
 @todo_item.update_attribute(:completed_at, Time.now)
 redirect_to @todo_list, notice: "Todo item completed"
end

private

def set_todo_list
 @todo_list = TodoList.find(params[:todo_list_id])
end

def set_todo_item
 @todo_item = @todo_list.todo_items.find(params[:id])
end

def todo_item_params
 params[:todo_item].permit(:content)
end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Todo" %>
 <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
	<% if @todo_item.completed? %>
		<div class="complete">
		 
			<%= link_to complete_todo_list_todo_item_path(@todo_list, @todo_item.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
			
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= @todo_item.content %></strike></p>
		</div>
		
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, @todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
		
	<% else %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, @todo_item.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		
		<div class="todo_item">
			<p><%= @todo_item.content %></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, @todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
		
	<% end %>
</div>