config/routes.rb
Rails.application.routes.draw do
  resources :userprojects
  get 'static_pages/home'

  resources :todo_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root   "users#home"
  get    '/users',        to: 'users#index' 
  get    '/users/edit',   to: 'users#edit'
  get    '/home',         to: 'users#home'
  get    '/signup',       to: 'users#new'
  get    'users/login',   to: 'sessions#new'
  post   'users/login',   to: 'sessions#create'
  delete 'users/logout',  to: 'sessions#destroy'
  resources :users

  root "users#new"
  get '/users',       to: 'users#index' 
  get '/users/new',   to: 'users#new'
  get '/users/edit',  to: 'users#edit'
  get '/users/signup',    to: 'users#signup'
resources :todo_lists do
   resources :todo_items do
    member do
     patch :complete
    end
  end
end


  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects,            only: [:create, :destroy]
  resources :following,           only: [:create, :destroy]
end

app/models/userproject.rb
class Userproject < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/controllers/userprojects_controller.rb
class UserprojectsController < ApplicationController
  before_action :set_userproject, only: [:show, :edit, :update, :destroy]

  # GET /userprojects
  # GET /userprojects.json
  def index
    @userprojects = Userproject.all
  end

  # GET /userprojects/1
  # GET /userprojects/1.json
  def show
  end

  # GET /userprojects/new
  def new
    @userproject = Userproject.new
  end

  # GET /userprojects/1/edit
  def edit
  end

  # POST /userprojects
  # POST /userprojects.json
  def create
    @userproject = Userproject.new(userproject_params)

    respond_to do |format|
      if @userproject.save
        format.html { redirect_to @userproject, notice: 'Userproject was successfully created.' }
        format.json { render :show, status: :created, location: @userproject }
      else
        format.html { render :new }
        format.json { render json: @userproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userprojects/1
  # PATCH/PUT /userprojects/1.json
  def update
    respond_to do |format|
      if @userproject.update(userproject_params)
        format.html { redirect_to @userproject, notice: 'Userproject was successfully updated.' }
        format.json { render :show, status: :ok, location: @userproject }
      else
        format.html { render :edit }
        format.json { render json: @userproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userprojects/1
  # DELETE /userprojects/1.json
  def destroy
    @userproject.destroy
    respond_to do |format|
      format.html { redirect_to userprojects_url, notice: 'Userproject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userproject
      @userproject = Userproject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userproject_params
      params.require(:userproject).permit(:title, :description)
    end
end

app/helpers/userprojects_helper.rb
module UserprojectsHelper
end

app/views/userprojects/_form.html.erb
<%= form_with(model: userproject, local: true) do |form| %>
  <% if userproject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userproject.errors.count, "error") %> prohibited this userproject from being saved:</h2>

      <ul>
      <% userproject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :userproject_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :userproject_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userprojects/edit.html.erb
<h1>Editing Userproject</h1>

<%= render 'form', userproject: @userproject %>

<%= link_to 'Show', @userproject %> |
<%= link_to 'Back', userprojects_path %>

app/views/userprojects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userprojects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userprojects.each do |userproject| %>
      <tr>
        <td><%= userproject.title %></td>
        <td><%= userproject.description %></td>
        <td><%= link_to 'Show', userproject %></td>
        <td><%= link_to 'Edit', edit_userproject_path(userproject) %></td>
        <td><%= link_to 'Destroy', userproject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userproject', new_userproject_path %>

app/views/userprojects/new.html.erb
<h1>New Userproject</h1>

<%= render 'form', userproject: @userproject %>

<%= link_to 'Back', userprojects_path %>

app/views/userprojects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @userproject.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @userproject.description %>
</p>

<%= link_to 'Edit', edit_userproject_path(@userproject) %> |
<%= link_to 'Back', userprojects_path %>