config/routes.rb
Rails.application.routes.draw do
  resources :userprojects
  get 'static_pages/home'

  resources :todo_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root   "users#home"
  get    '/users',        to: 'users#index' 
  get    '/users/edit',   to: 'users#edit'
  get    '/home',         to: 'users#home'
  get    '/signup',       to: 'users#new'
  get    'users/login',   to: 'sessions#new'
  post   'users/login',   to: 'sessions#create'
  delete 'users/logout',  to: 'sessions#destroy'
  resources :users

  root "users#new"
  get '/users',       to: 'users#index' 
  get '/users/new',   to: 'users#new'
  get '/users/edit',  to: 'users#edit'
  get '/users/signup',    to: 'users#signup'
resources :todo_lists do
   resources :todo_items do
    member do
     patch :complete
    end
  end
end


  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :projects,            only: [:create, :destroy]
  resources :following,           only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
   has_many :user_projects, foreign_key: "user_id"
   has_many :projects, through: :user_projects
   has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    
#   before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
#   before_action :correct_user,   only: [:edit, :update]
#   before_action :admin_user,     only: :destroy 
  
    def index
        # @users = User.where(activated: true).paginate(page: params[:page])
    end
    
    def show
        @user = User.find(params[:id])
        @microposts = @user.microposts.paginate(page: params[:page])
    end
    
    def new
      @user = User.new
    end
    


    def show
    @user = User.find(params[:id])
    @projects = @user.projects.paginate(page: params[:page])
    end


    
    def edit
        @user = User.find(params[:id])
    end
    
    def login
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:info] = "Please check your email to activate your account."
            redirect_to root_url
        else
            render 'new'
        end
        
    end
    
    def update
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated"
            redirect_to @user
        else
            render 'edit'
        end
    end
    
    
    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>

<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      
      <a href="http://gravatar.com/emails" target="_blank">Change</a>

    </div>
  </div>
</div>

app/views/users/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Capstone Project</h1>
  
    <h2>
      This is the home page for the
      <p>Ruby on Rails Tutorial</p>
      
    </h2>
  
    <%= link_to "Sign up!", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "sign In!", users_edit_path, class: "btn btn-lg btn-primary" %>
  </div>

app/views/users/login.html.erb
Login page

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.projects.any? %>
      <h3>Projects (<%= @user.projects.count %>)</h3>
      <ol class="projects">
        <%= render @projects %>
      </ol>
      <%= will_paginate @projects %>
    <% end %>
  </div>
</div>